name: Create release and publish docker image

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@main
  publish:
    needs: release
    uses: remla23-team5/cicd/.github/workflows/publish-docker.yaml@main
    with:
      IMAGE_NAME: ${{ github.repository }}
